### ISSUE TITLE
Al crear un álbum no muestra mensaje de alerta cuando no se puede crear

### ISSUE THREAD

**Issue by CristinaGM4** [JuliethQP/IngenieriaSoftwareAppsMoviles#22]
Al llenar los campos de la creación de álbum con datos inválidos, permite dar clic en Crear álbum y no lo crea, pero no muestra al usuario un aviso en el que diga que no se creó el álbum o indique cuáles campos de datos son inválidos.

**Comment by devsjuanh** [comment]
Se realiza el ajuste.
