### ISSUE TITLE
Actualizar readme

### ISSUE THREAD

**Issue by JuliethQP** [JuliethQP/IngenieriaSoftwareAppsMoviles#24]
comentario tutor : Y sobre lo de que la app no compilaba, me dí cuenta de que es porque algo hacen que en android L específicamente falla, esto puesto que probé con android 11 y sirvió, eso también significa que las instrucciones del readme están incompletas porque no advierten sobre eso

**Comment by devsjuanh** [comment]
SE REALIZA EL AJUSTE.
